site_name: Forta Developer SDK

nav:
  - Overview: index.md
  - Build your first agent:
      - 1) Quick start: quickstart.md
      - 2) Testing your agent: testing.md
      - 3) Deploying your agent: deploying.md
  - Reference:
      - Core concepts: concepts.md
      - CLI commands: cli.md
      - forta.config.json: config.md
  - Javascript SDK: sdk.md
  - Python SDK: python.md
  - Private agents: private.md
  - Getting help: help.md
  - Best practices: best-practices.md
  - FAQ: faq.md
  - Agent Developer Contests:
      - Contest 1 (10/20/2021): contest1.md

theme:
  name: material
  palette:
    primary: black
    accent: blue grey
  logo: forta-logo.png
  favicon: forta-logo.png
  features:
    - navigation.expand
    - navigation.instant

markdown_extensions:
  - admonition
